# Generated by Django 5.0.8 on 2024-08-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='', upload_to='image'),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
